package fr.lapetina.music.exercise;

public enum ExerciseType {
    NAME_NOTE,
    IDENTIFY_INTERVAL,
    BUILD_INTERVAL,
    SPELL_SCALE,
    PLAY_SCALE,
    KEY_SIGNATURE,
    NAME_SCALE_DEGREE,
    IDENTIFY_MODE,
    SPELL_CHORD,
    PLAY_CHORD,
    PLAY_INVERSION,
    NAME_BASS_NOTE,
    CHORD_QUALITY_IN_KEY,
    ROMAN_NUMERAL,
    FIGURED_BASS,
    IDENTIFY_TRITONE,
    IDENTIFY_CADENCE,
    HARMONIC_FUNCTION,
    RESOLVE_TENDENCY_TONE,
    PIVOT_CHORD,
    SECONDARY_DOMINANT,
    EXPLAIN
}
