package fr.lapetina.music.concept;

import fr.lapetina.music.learner.ConceptMastery;
import fr.lapetina.music.learner.LearnerSnapshot;
import fr.lapetina.music.theory.AbcNotation;
import fr.lapetina.music.theory.Chord;
import fr.lapetina.music.theory.ChordAnalyzer;
import fr.lapetina.music.theory.ChordQuality;
import fr.lapetina.music.theory.Interval;
import fr.lapetina.music.theory.Inversion;
import fr.lapetina.music.theory.Key;
import fr.lapetina.music.theory.Mode;
import fr.lapetina.music.theory.PitchClass;
import fr.lapetina.music.theory.RomanNumeralAnalyzer;
import fr.lapetina.music.theory.Scale;
import fr.lapetina.music.theory.ScaleType;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Teaches a concept, before anything is asked about it.
 *
 * <p>Every fact and every worked example is generated by the theory engine, so the lesson
 * and the marking cannot disagree. A language model is not involved: this is the part of
 * the application that must simply be right.
 */
@ApplicationScoped
public class LessonService {

    @Inject
    ConceptGraph conceptGraph;

    public Lesson lessonFor(String conceptId, LearnerSnapshot snapshot) {
        Concept concept = conceptGraph.require(conceptId);
        ConceptMastery mastery = snapshot.concept(conceptId);
        boolean ready = concept.prerequisites().stream().allMatch(snapshot::knows);

        return new Lesson(
                concept.id(),
                concept.name(),
                concept.description(),
                concept.category().name(),
                sectionsFor(conceptId),
                links(concept.prerequisites(), snapshot),
                links(conceptGraph.dependentsOf(conceptId).stream().map(Concept::id).toList(), snapshot),
                mastery.mastery(),
                mastery.state().name(),
                ready);
    }

    private List<Lesson.ConceptLink> links(List<String> ids, LearnerSnapshot snapshot) {
        List<Lesson.ConceptLink> links = new ArrayList<>();
        for (String id : ids) {
            ConceptMastery mastery = snapshot.concept(id);
            links.add(new Lesson.ConceptLink(id, mastery.name(), mastery.mastery(), mastery.isKnown()));
        }
        return List.copyOf(links);
    }

    /** Root, third and seventh: the notes a shell voicing keeps. */
    private static String shell(String root, ChordQuality quality) {
        var classes = Chord.of(root, quality).pitchClasses();
        return classes.get(0).name() + " " + classes.get(1).name() + " " + classes.get(3).name();
    }

    private static String spell(Scale scale) {
        return scale.pitchClasses().stream().map(PitchClass::name).collect(Collectors.joining(" "));
    }

    private static String notes(Chord chord) {
        return chord.pitchClasses().stream().map(PitchClass::name).collect(Collectors.joining(" "));
    }

    private static String chordLine(Key key, int... degrees) {
        List<Chord> chords = new ArrayList<>();
        for (int degree : degrees) {
            chords.add(key.triad(degree));
        }
        return chords.stream().map(Chord::symbol).collect(Collectors.joining(" "));
    }

    private static List<Chord> chords(String... symbols) {
        return List.of(symbols).stream().map(ChordAnalyzer::parse).toList();
    }

    /** The body of the lesson, per concept. */
    List<LessonSection> sectionsFor(String conceptId) {
        Key c = Key.major("C");
        return switch (conceptId) {
            case "note" -> List.of(
                    LessonSection.of("Seven letters, then they repeat",
                            "Music uses only A B C D E F G. After G it starts again at A, an octave higher.",
                            "On a piano, the white keys are those seven letters. The black keys are the notes between."),
                    LessonSection.of("Sharps raise, flats lower",
                            "A sharp (#) raises a note by one semitone — the very next key up, black or white.",
                            "A flat (b) lowers it by one semitone.",
                            "So the black key between C and D is both C# and Db. Same key, two names."),
                    LessonSection.of("Why two names matter",
                            "F# and Gb sound identical but are not interchangeable. Which one is correct depends on the key you are in.",
                            "This is called spelling, and getting it wrong is the most common mistake in written harmony.")
                            .showing(AbcNotation.melody(List.of(
                                    fr.lapetina.music.theory.Note.parse("C4"),
                                    fr.lapetina.music.theory.Note.parse("C#4"),
                                    fr.lapetina.music.theory.Note.parse("D4"),
                                    fr.lapetina.music.theory.Note.parse("Eb4")), c, "Semitone steps"),
                                    "C, C sharp, D, E flat — each a semitone apart"));

            case "interval" -> List.of(
                    LessonSection.of("An interval is a distance, named twice over",
                            "Every interval has a number and a quality. The number counts letter names; the quality says exactly how wide.",
                            "C up to E spans C-D-E, three letters, so it is a third. It is four semitones wide, which makes it major.",
                            "C up to Eb is still a third — same three letters — but three semitones, which makes it minor."),
                    LessonSection.of("Perfect, major and minor",
                            "Unisons, fourths, fifths and octaves are perfect. Seconds, thirds, sixths and sevenths are major or minor.",
                            "Narrowing a perfect or minor interval makes it diminished. Widening any of them makes it augmented."),
                    LessonSection.of("Where spelling bites",
                            "C to F# is an augmented fourth. C to Gb is a diminished fifth. Both are six semitones.",
                            "They are different intervals because the letters differ, and they behave differently in harmony.")
                            .showing(AbcNotation.interval(fr.lapetina.music.theory.Note.parse("C4"),
                                    Interval.MAJOR_THIRD, c), "A major third above C"));

            case "major-scale" -> List.of(
                    LessonSection.of("One pattern, twelve keys",
                            "Tone, tone, semitone, tone, tone, tone, semitone. That pattern is the major scale, wherever you start.",
                            "C major: " + spell(Scale.of("C", ScaleType.MAJOR)) + " — the only one with no sharps or flats.",
                            "D major: " + spell(Scale.of("D", ScaleType.MAJOR)) + ". The pattern forces F# and C#."),
                    LessonSection.of("One note per letter",
                            "A major scale uses each letter exactly once. That is why F# major has an E#, not an F.",
                            "F# major: " + spell(Scale.of("F#", ScaleType.MAJOR)) + ".")
                            .showing(AbcNotation.scale(Scale.of("D", ScaleType.MAJOR), 4), "D major, ascending"));

            case "minor-scale" -> List.of(
                    LessonSection.of("Three forms, one tonic",
                            "Natural minor: " + spell(Scale.of("A", ScaleType.NATURAL_MINOR)) + ".",
                            "Harmonic minor raises the seventh: " + spell(Scale.of("A", ScaleType.HARMONIC_MINOR)) + ".",
                            "Melodic minor raises the sixth as well: " + spell(Scale.of("A", ScaleType.MELODIC_MINOR)) + "."),
                    LessonSection.of("Why the seventh gets raised",
                            "Without it there is no leading tone, and no semitone pulling up to the tonic.",
                            "Raising it also turns the chord on the fifth degree from minor into major, which is what makes a minor key sound like it has a dominant.")
                            .showing(AbcNotation.scale(Scale.of("A", ScaleType.HARMONIC_MINOR), 4),
                                    "A harmonic minor — note the G sharp"));

            case "triad" -> List.of(
                    LessonSection.of("Two thirds, stacked",
                            "Take a note, add a third above it, then another third above that. That is a triad.",
                            "Which thirds you stack decides the quality."),
                    LessonSection.of("The four qualities",
                            "Major: " + notes(Chord.of("C", ChordQuality.MAJOR)) + " — major third, then minor third.",
                            "Minor: " + notes(Chord.of("C", ChordQuality.MINOR)) + " — minor third, then major third.",
                            "Diminished: " + notes(Chord.of("C", ChordQuality.DIMINISHED)) + " — two minor thirds.",
                            "Augmented: " + notes(Chord.of("C", ChordQuality.AUGMENTED)) + " — two major thirds.")
                            .showing(AbcNotation.progression(chords("C", "Cm", "Cdim", "Caug"), c, AbcNotation.CHORD_OCTAVE),
                                    "The same root, four qualities"));

            case "chord-inversion" -> List.of(
                    LessonSection.of("The bass decides",
                            "A chord is inverted when something other than the root is the lowest note.",
                            "G major has the notes G B D. In root position G is lowest; in first inversion B is; in second inversion D is.",
                            "The order of the notes above the bass makes no difference at all."),
                    LessonSection.of("How they are written",
                            "First inversion is figured 6, second inversion 6/4. In lead sheets you will see G/B and G/D.",
                            "For seventh chords the figures are 7, 6/5, 4/3 and 4/2 from root position downwards.")
                            .showing(AbcNotation.progression(chords("G", "G/B", "G/D"), c, AbcNotation.CHORD_OCTAVE),
                                    "G major: root position, first inversion, second inversion"));

            case "seventh-chord" -> List.of(
                    LessonSection.of("A third on top of a triad",
                            "Add one more third above a triad and you have a seventh chord.",
                            "Dominant seventh: " + notes(Chord.of("G", ChordQuality.DOMINANT_SEVENTH)) + " — major triad, minor seventh.",
                            "Major seventh: " + notes(Chord.of("C", ChordQuality.MAJOR_SEVENTH)) + " — major triad, major seventh.",
                            "Minor seventh: " + notes(Chord.of("D", ChordQuality.MINOR_SEVENTH)) + " — minor triad, minor seventh."),
                    LessonSection.of("The two diminished kinds",
                            "Half-diminished: " + notes(Chord.of("B", ChordQuality.HALF_DIMINISHED_SEVENTH)) + " — diminished triad, minor seventh.",
                            "Fully diminished: " + notes(Chord.of("B", ChordQuality.DIMINISHED_SEVENTH)) + " — diminished triad, diminished seventh.")
                            .showing(AbcNotation.progression(chords("Cmaj7", "Dm7", "G7", "Bm7b5"), c, AbcNotation.CHORD_OCTAVE),
                                    "Four seventh chords from C major"));

            case "roman-numeral" -> List.of(
                    LessonSection.of("Numbering chords, not notes",
                            "A Roman numeral names a chord by the scale degree it is built on, so harmony can be described in any key at once.",
                            "Upper case means a major third in the chord, lower case a minor one. A small circle means diminished."),
                    LessonSection.of("The seven of a major key",
                            "In C major: " + chordLine(c, 1, 2, 3, 4, 5, 6, 7),
                            "Numbered: I ii iii IV V vi vii°. That pattern of qualities is the same in every major key.")
                            .showing(AbcNotation.progression(c.diatonicTriads(), c, AbcNotation.CHORD_OCTAVE),
                                    "The seven diatonic triads of C major"));

            case "dominant-seventh" -> List.of(
                    LessonSection.of("The chord that has to move",
                            "V7 is built on the fifth degree: in C major, " + notes(c.dominantSeventh()) + ".",
                            "Inside it sits a tritone — between the third and the seventh — and that interval is unstable."),
                    LessonSection.of("How it resolves",
                            "The third is the leading tone and rises a semitone to the tonic.",
                            "The seventh falls a step to the third of the tonic chord.",
                            "In C: B rises to C, F falls to E. Both move as little as possible.")
                            .showing(AbcNotation.progression(List.of(c.dominantSeventh(), c.tonicTriad()), c, AbcNotation.CHORD_OCTAVE),
                                    "G7 resolving to C"));

            case "cadence" -> List.of(
                    LessonSection.of("How a phrase ends",
                            "A cadence is the harmonic punctuation at the end of a phrase, and how strongly it closes.",
                            "Perfect authentic: V to I, both in root position. The strongest ending there is.",
                            "Half: the phrase stops on V. Unfinished, and meant to be.",
                            "Plagal: IV to I. The amen.",
                            "Deceptive: V to vi. Sets up the ending, then withholds it.")
                            .showing(AbcNotation.progression(chords("F", "G", "C"), c, AbcNotation.CHORD_OCTAVE),
                                    "IV V I — a perfect authentic cadence in C"));

            case "extended-chord" -> List.of(
                    LessonSection.of("Keep stacking thirds",
                            "Above the seventh come the ninth, the eleventh and the thirteenth.",
                            "C9: " + notes(Chord.of("C", ChordQuality.DOMINANT_NINTH)) + ".",
                            "Cmaj9: " + notes(Chord.of("C", ChordQuality.MAJOR_NINTH)) + ".",
                            "C13: " + notes(Chord.of("C", ChordQuality.DOMINANT_THIRTEENTH)) + "."),
                    LessonSection.of("Sixths are not sevenths",
                            "C6 is " + notes(Chord.of("C", ChordQuality.MAJOR_SIXTH)) + " — a triad with a sixth added, not a chord with a seventh.",
                            "It is a resting chord where a seventh would want to move.")
                            .showing(AbcNotation.progression(chords("C6", "C9", "Cmaj9"), c, AbcNotation.CHORD_OCTAVE),
                                    "C6, C9 and Cmaj9"));

            case "altered-dominant" -> List.of(
                    LessonSection.of("Sharpening the tension",
                            "A dominant already wants to resolve. Altering its ninth, eleventh or thirteenth makes it want to more.",
                            "C7b9: " + notes(Chord.of("C", ChordQuality.DOMINANT_FLAT_NINTH)) + ".",
                            "C7#9: " + notes(Chord.of("C", ChordQuality.DOMINANT_SHARP_NINTH)) + ".",
                            "C7#11: " + notes(Chord.of("C", ChordQuality.DOMINANT_SHARP_ELEVENTH)) + ".",
                            "C7b13: " + notes(Chord.of("C", ChordQuality.DOMINANT_FLAT_THIRTEENTH)) + "."),
                    LessonSection.of("Spelling still matters",
                            "The sharp ninth of C7 is D#, not Eb. It is a raised second degree, so it is spelled as one.",
                            "The chord still functions as a dominant: the alterations sharpen it, they do not change its job."));

            case "key-signature" -> List.of(
                    LessonSection.of("The accidentals a key always has",
                            "Rather than write a sharp before every F in D major, the key signature says it once at the start and it holds for the whole piece.",
                            "D major is " + spell(Scale.of("D", ScaleType.MAJOR)) + ", so its signature is two sharps: F# and C#."),
                    LessonSection.of("They accumulate in a fixed order",
                            "Sharps arrive F C G D A E B; flats arrive in the reverse, B E A D G C F.",
                            "So one sharp is G major, two is D, three is A. One flat is F major, two is Bb, three is Eb.",
                            "The order is not arbitrary: each new key is a fifth away from the last, and a fifth up adds exactly one sharp."),
                    LessonSection.of("Relative minors share a signature",
                            "A minor key uses the signature of the major a minor third above it. " + Key.major("C").relative().name() + " and C major both have none.",
                            "Which of the two you are in is decided by the music, not the signature."));

            case "scale-degree" -> List.of(
                    LessonSection.of("Every note of a key has a job",
                            "Numbered from the tonic: 1 tonic, 2 supertonic, 3 mediant, 4 subdominant, 5 dominant, 6 submediant, 7 leading tone.",
                            "In C major that is " + spell(Scale.of("C", ScaleType.MAJOR)) + " in order."),
                    LessonSection.of("The names describe the pull, not the position",
                            "The leading tone is called that because it leads: a semitone below the tonic, it wants to rise to it. In C that is B going to C.",
                            "The dominant is the strongest note after the tonic, and the chord built on it is what makes an ending sound like an ending.",
                            "In a natural minor the seventh is a whole tone below the tonic and does not pull the same way, which is why the harmonic minor raises it."));

            case "diatonic-triads" -> List.of(
                    LessonSection.of("Seven notes, seven chords",
                            "Stack thirds on each degree of the scale, using only notes from the key, and you get the chords that key contains.",
                            "In C major: " + chordLine(c, 1, 2, 3, 4, 5, 6, 7) + "."),
                    LessonSection.of("The pattern is the same in every major key",
                            "Major, minor, minor, major, major, minor, diminished. Learn it once and it transfers to all twelve keys.",
                            "In G major the same pattern gives " + chordLine(Key.major("G"), 1, 2, 3, 4, 5, 6, 7) + ".")
                            .showing(AbcNotation.progression(c.diatonicTriads(), c, AbcNotation.CHORD_OCTAVE),
                                    "the seven triads of C major"));

            case "mode" -> List.of(
                    LessonSection.of("The same notes, a different home",
                            "Play the white keys from D to D and you get D Dorian: " + spell(Scale.of("D", ScaleType.DORIAN)) + ".",
                            "The notes are C major's. What changed is which one feels like home, and that changes everything about how they sound."),
                    LessonSection.of("What gives each mode its character",
                            "Dorian is minor with a raised sixth: " + spell(Scale.of("D", ScaleType.DORIAN)) + " against D natural minor's " + spell(Scale.of("D", ScaleType.NATURAL_MINOR)) + ".",
                            "Lydian is major with a raised fourth: " + spell(Scale.of("F", ScaleType.LYDIAN)) + ".",
                            "Mixolydian is major with a lowered seventh: " + spell(Scale.of("G", ScaleType.MIXOLYDIAN)) + ".",
                            "One note is usually the whole difference, and it is worth knowing which."));

            case "figured-bass" -> List.of(
                    LessonSection.of("Numbers under the bass",
                            "Figures say what intervals sit above the written bass note, not what the chord is called. The player works out the rest.",
                            "A bare bass note means a root-position triad. A 6 means the third is in the bass; a 6/4 means the fifth is."),
                    LessonSection.of("Reading the common figures",
                            "For triads: nothing, 6, 6/4. For sevenths: 7, 6/5, 4/3, 4/2.",
                            "So " + notes(Chord.of("G", ChordQuality.DOMINANT_SEVENTH)) + " written as V6/5 puts B in the bass.",
                            "It is a shorthand for improvising an accompaniment, which is what it was invented for."));

            case "harmonic-function" -> List.of(
                    LessonSection.of("Chords do jobs, and there are only three",
                            "Tonic is home. Predominant leaves it. Dominant pulls back. Almost all common-practice harmony is that cycle, repeated.",
                            "In C major: " + chordLine(c, 1) + " is tonic, " + chordLine(c, 4, 2) + " are predominant, " + chordLine(c, 5, 7) + " are dominant."),
                    LessonSection.of("Function explains substitution",
                            "Two chords with the same function can often stand in for each other, because the job matters more than the notes.",
                            "IV and ii both lead to V. I and vi both feel like arrival, which is why V-vi sounds like an ending that was withheld.")
                            .showing(AbcNotation.progression(chords("C", "F", "G", "C"), c, AbcNotation.CHORD_OCTAVE),
                                    "tonic, predominant, dominant, tonic"));

            case "tonic-function" -> List.of(
                    LessonSection.of("Home",
                            "The tonic chord is where a passage is at rest. Everything else is heard in relation to it.",
                            "In C major that is " + chordLine(c, 1) + "."),
                    LessonSection.of("Its neighbours share the feeling",
                            "iii and vi share two notes with the tonic triad, so they can stand in for it: " + chordLine(c, 1, 3, 6) + ".",
                            "That is why a phrase ending on vi still sounds like an arrival, just not a final one."));

            case "predominant-function" -> List.of(
                    LessonSection.of("The chord before the dominant",
                            "Predominants set up the dominant. They are what makes an ending feel prepared rather than abrupt.",
                            "The main two in C major are " + chordLine(c, 4, 2) + "."),
                    LessonSection.of("ii or IV",
                            "They share two notes, so they do the same job. ii moves to V by a fifth, which is stronger; IV moves by a step, which is smoother.",
                            "In jazz the ii is almost always chosen, with a seventh on it: " + notes(Chord.of("D", ChordQuality.MINOR_SEVENTH)) + ".")
                            .showing(AbcNotation.progression(chords("Dm", "G", "C"), c, AbcNotation.CHORD_OCTAVE),
                                    "ii - V - I in C major"));

            case "dominant-function" -> List.of(
                    LessonSection.of("The chord that wants to resolve",
                            "The dominant is built on the fifth degree: " + chordLine(c, 5) + " in C major. Add its seventh and it becomes " + notes(c.dominantSeventh()) + ".",
                            "It contains the leading tone, which pulls up to the tonic, and with the seventh a tritone, which pulls inward."),
                    LessonSection.of("Why the tritone decides everything",
                            "In G7 the tritone is B and F. B rises to C, F falls to E, and you have landed on C major almost inevitably.",
                            "vii° does the same job with the same tritone and no root: " + chordLine(c, 7) + ".")
                            .showing(AbcNotation.progression(List.of(c.dominantSeventh(), c.tonicTriad()), c, AbcNotation.CHORD_OCTAVE),
                                    "G7 resolving to C"));

            case "secondary-dominant" -> List.of(
                    LessonSection.of("Borrowing a dominant from another key",
                            "Any chord can be made to feel like a temporary home by putting its own dominant in front of it.",
                            "The dominant of C is G. So the dominant of G — the dominant of the dominant — is D, and we write it V/V.",
                            "In C major, V7/V is " + notes(RomanNumeralAnalyzer.realize("V7/V", c)) + "."),
                    LessonSection.of("The accidental is the giveaway",
                            "V7/V in C contains F#, which is not in C major. That sharp is the leading tone of G, and it is what makes G sound momentarily like home.",
                            "Any chord borrowed this way brings the accidental its target key needs. That is how you spot one on the page.")
                            .showing(AbcNotation.progression(chords("C", "D7", "G", "C"), c, AbcNotation.CHORD_OCTAVE),
                                    "I - V7/V - V - I in C major"),
                    LessonSection.of("It tonicises without modulating",
                            "A secondary dominant points at a chord for a moment and then moves on. The key has not changed.",
                            "When the music stays in the new key and cadences there, that is modulation, which is a larger claim."));

            case "chord-progression" -> List.of(
                    LessonSection.of("Chords in order, not in isolation",
                            "A progression is a sequence that goes somewhere. Root motion down a fifth is the strongest step there is, which is why ii-V-I and vi-ii-V-I feel inevitable.",
                            "In C major: " + String.join(" ", chords("Dm", "G", "C").stream().map(ch -> ch.symbol()).toList()) + "."),
                    LessonSection.of("Common shapes worth knowing by ear",
                            "I-IV-V-I is the plain cadential shape. I-vi-IV-V is the one behind a great deal of popular music.",
                            "vi-ii-V-I is the same falling-fifths motion extended backwards, and is the backbone of a jazz standard.")
                            .showing(AbcNotation.progression(chords("C", "Am", "F", "G"), c, AbcNotation.CHORD_OCTAVE),
                                    "I - vi - IV - V in C major"));

            case "modal-interchange" -> List.of(
                    LessonSection.of("Borrowing from the parallel minor",
                            "C major and C minor share a tonic. Chords from the minor can be used in the major without leaving the key.",
                            "The common borrowings are " + chordLine(Key.minor("C"), 4) + ", " + notes(Chord.of("Ab", ChordQuality.MAJOR)) + " as bVI, and " + notes(Chord.of("Eb", ChordQuality.MAJOR)) + " as bIII."),
                    LessonSection.of("What it sounds like",
                            "A borrowed iv in a major key is the classic sudden darkening — the same chord you expected, one note lower.",
                            "It is not modulation: nothing cadences in the minor, and the tonic never changes.")
                            .showing(AbcNotation.progression(chords("C", "Fm", "C"), c, AbcNotation.CHORD_OCTAVE),
                                    "a borrowed iv in C major"));

            case "voice-leading" -> List.of(
                    LessonSection.of("Move as little as possible",
                            "When one chord goes to the next, each voice should move to the nearest available note. Common tones are held.",
                            "G7 to C: the B rises a semitone to C, the F falls a semitone to E, the G stays. Only the bass leaps."),
                    LessonSection.of("The rules worth keeping",
                            "Resolve the leading tone upward. Resolve the seventh downward. Avoid parallel fifths and octaves between any two voices.",
                            "These are conventions of one tradition, not laws of music — but within that tradition they are what makes four parts sound like four independent lines rather than a stack of chords."));

            case "blues-form" -> List.of(
                    LessonSection.of("Twelve bars, three chords",
                            "Four bars of I, two of IV, two of I, then V, IV, I, and a bar to turn around.",
                            "In C: " + String.join(" ", chords("C7", "F7", "G7").stream().map(ch -> ch.symbol()).toList()) + " — and note that all three are dominant sevenths."),
                    LessonSection.of("Why every chord is a seventh",
                            "In common-practice harmony a dominant seventh must resolve. In the blues it does not: I7 is home, and stays home.",
                            "That is the clearest case of a rule belonging to a tradition rather than to music. The blues did not break it; it was never playing that game.")
                            .showing(AbcNotation.progression(chords("C7", "F7", "C7", "G7"), c, AbcNotation.CHORD_OCTAVE),
                                    "the shape of a blues in C"));

            case "modulation" -> List.of(
                    LessonSection.of("Changing key, and meaning it",
                            "A modulation moves the tonic. Afterwards the music is heard in a new key, and it usually takes a cadence there to convince the ear.",
                            "The nearest keys are a fifth away — C to G, or C to F — because they differ by a single accidental."),
                    LessonSection.of("The pivot chord",
                            "The smooth way across is a chord both keys contain. " + chordLine(c, 6) + " is vi in C major and ii in G major, so it can be heard either way.",
                            "Play it as vi, then treat it as ii, and follow with G major's own V-I. The join is inaudible, which is the point.")
                            .showing(AbcNotation.progression(chords("C", "Am", "D7", "G"), c, AbcNotation.CHORD_OCTAVE),
                                    "C major pivoting to G major through Am"));

            case "chord-symbol" -> List.of(
                    LessonSection.of("A symbol is a recipe, not a picture",
                            "A chord symbol names a root and a quality, and leaves the arrangement to you. Cmaj7 tells you which notes; it does not tell you which octave, which order, or which to leave out.",
                            "That is why the same tune looks the same on every lead sheet and sounds different in every pair of hands."),
                    LessonSection.of("Reading the shorthand",
                            "The root comes first, then the quality: " + notes(Chord.of("C", ChordQuality.MAJOR_SEVENTH))
                                    + " is Cmaj7, and " + notes(Chord.of("C", ChordQuality.DOMINANT_SEVENTH)) + " is C7.",
                            "A bare number means a dominant. 'maj' or a triangle means a major seventh. A minus or 'm' means minor, and a circle means diminished.",
                            "Half-diminished is written with a slashed circle, or as m7b5: " + notes(Chord.of("C", ChordQuality.HALF_DIMINISHED_SEVENTH)) + ".")
                            .showing(AbcNotation.progression(chords("Cmaj7", "C7", "Cm7", "Cm7b5"), c, AbcNotation.CHORD_OCTAVE),
                                    "four qualities on the same root"),
                    LessonSection.of("Extensions and alterations",
                            "A 9, 11 or 13 stacks another third on top. An alteration in brackets bends one note: " + notes(Chord.of("G", ChordQuality.DOMINANT_FLAT_NINTH)) + " is G7(b9).",
                            "A slash names the bass: C/E means a C chord with E underneath, which is a first inversion by another name."));

            case "jazz-voicing" -> List.of(
                    LessonSection.of("The two notes that carry the sound",
                            "The third tells you major or minor. The seventh tells you which kind of seventh. The root is usually the bass player's job, and the fifth says almost nothing.",
                            "So the smallest useful voicing is root, third and seventh — a shell."),
                    LessonSection.of("Shells",
                            "For G7 that is " + shell("G", ChordQuality.DOMINANT_SEVENTH) + ". For Cmaj7 it is " + shell("C", ChordQuality.MAJOR_SEVENTH) + ".",
                            "Play a ii-V-I with shells and the voice leading appears on its own: the notes barely move.")
                            .showing(AbcNotation.progression(chords("Dm7", "G7", "Cmaj7"), c, AbcNotation.CHORD_OCTAVE),
                                    "the same ii-V-I a shell voicing simplifies"),
                    LessonSection.of("Rootless voicings",
                            "Drop the root entirely and you have room for the ninth or the thirteenth instead.",
                            "This is why a jazz pianist's left hand often sounds like a different chord from the one written: it is the same chord, minus what somebody else is already playing."));

            case "chord-scale-theory" -> List.of(
                    LessonSection.of("A chord and a scale are the same information",
                            "Every chord tone is a scale degree, and the notes between them are the ones you pass through. Choosing a scale for a chord is choosing which notes are available.",
                            "This is a way of practising, not a law. Players who never think in scales play the same notes."),
                    LessonSection.of("The usual pairings",
                            "Over a dominant seventh: Mixolydian. " + spell(Scale.of("G", ScaleType.MIXOLYDIAN)) + " over G7.",
                            "Over a minor seventh: Dorian. " + spell(Scale.of("D", ScaleType.DORIAN)) + " over Dm7.",
                            "Over a major seventh: Ionian, or Lydian if you want the raised fourth."),
                    LessonSection.of("When the chord is altered",
                            "An altered dominant asks for the altered scale, which is every tension at once: " + spell(Scale.of("G", ScaleType.ALTERED)) + " over G7alt.",
                            "Note the spelling: the fourth degree is C flat, not B. It is a diminished fourth above G, and writing it as B would hide that it is the flattened fourth of the scale."));

            case "turnaround" -> List.of(
                    LessonSection.of("Getting back to the top",
                            "A chorus ends on the tonic, and then has to start again. A turnaround is the bar or two that makes returning feel like motion rather than repetition.",
                            "The plain form is I-vi-ii-V: " + chordLine(c, 1, 6, 2, 5) + "."),
                    LessonSection.of("Decorating it",
                            "Make the vi a dominant and it pulls harder toward the ii. Make the I a I7 and it pulls toward IV.",
                            "Substitute a tritone for any of the dominants and the bass walks down by semitone instead of leaping by fourths.")
                            .showing(AbcNotation.progression(chords("Cmaj7", "Am7", "Dm7", "G7"), c, AbcNotation.CHORD_OCTAVE),
                                    "I-vi-ii-V in C"));

            case "blues-scale" -> List.of(
                    LessonSection.of("The minor pentatonic, plus one",
                            "The blues scale is the minor pentatonic with a flat fifth added: " + spell(Scale.of("C", ScaleType.BLUES)) + " on C.",
                            "That added note is the blue note. It does not belong to the underlying harmony, and that is the point of it."),
                    LessonSection.of("Why it works over everything",
                            "In a blues, the same scale is played over I7, IV7 and V7, which would be wrong by any other reckoning.",
                            "It sounds right because the blues is not really functional harmony being decorated; it is a melodic tradition that harmony was fitted to afterwards.")
                            .showing(AbcNotation.scale(Scale.of("C", ScaleType.BLUES), 4), "the C blues scale"));

            case "two-five-one" -> List.of(
                    LessonSection.of("The sentence jazz is written in",
                            "ii-V-I is a predominant, then a dominant, then home — the same shape as classical harmony, with sevenths on everything.",
                            "In C: Dm7 G7 Cmaj7. In F: Gm7 C7 Fmaj7. In Bb: Cm7 F7 Bbmaj7."),
                    LessonSection.of("Why it holds together",
                            "Each chord's seventh falls a semitone and lands on the next chord's third.",
                            "In C: the seventh of Dm7 is C, and it falls to B, the third of G7. The seventh of G7 is F, and it falls to E, the third of Cmaj7.",
                            "That chain of falling sevenths is the whole mechanism, and it is why the progression feels inevitable rather than merely conventional.",
                            "In a minor key the ii is half-diminished: Dm7b5 G7 Cm7.")
                            .showing(AbcNotation.progression(chords("Dm7", "G7", "Cmaj7"), c, AbcNotation.CHORD_OCTAVE),
                                    "ii-V-I in C major"));

            case "tritone-substitution" -> List.of(
                    LessonSection.of("Two dominants, one tritone",
                            "G7 contains B and F. Db7 contains F and Cb, which sounds the same as B.",
                            "They share the tritone that wants to resolve, so either can resolve to C."),
                    LessonSection.of("What changes",
                            "The bass. Instead of falling a fifth from G to C, it slides a semitone from Db to C.",
                            "In C major, Dm7 Db7 Cmaj7 is a ii-V-I with the dominant substituted.")
                            .showing(AbcNotation.progression(chords("Dm7", "Db7", "Cmaj7"), c, AbcNotation.CHORD_OCTAVE),
                                    "ii-V-I with a tritone substitution"));

            case "counterpoint" -> List.of(
                    LessonSection.of("Two lines, both alive",
                            "Counterpoint is two melodies heard at once, each one worth listening to on its own.",
                            "What keeps them independent is how they move in relation to each other."),
                    LessonSection.of("Four motions",
                            "Parallel: both move the same way, keeping the same interval.",
                            "Similar: both move the same way, but the interval changes.",
                            "Contrary: they move in opposite directions. The most independent.",
                            "Oblique: one moves, the other holds."),
                    LessonSection.of("The forbidden parallel",
                            "Two voices moving from a perfect fifth straight into another perfect fifth stop sounding like two voices.",
                            "Same for octaves. Parallel thirds and sixths are fine, and common.",
                            "Reach a perfect consonance by contrary motion instead."));

            case "species-counterpoint" -> List.of(
                    LessonSection.of("First species: note against note",
                            "One note in your line for each note of the given melody, the cantus firmus.",
                            "Every one of them a consonance."),
                    LessonSection.of("What counts as consonant",
                            "Unisons, thirds, perfect fifths, sixths and octaves.",
                            "Seconds, fourths, sevenths and any tritone are dissonant and are not allowed here."),
                    LessonSection.of("Beginning and ending",
                            "Start on a perfect consonance and end on one.",
                            "Approach the final by contrary motion, and prefer contrary motion throughout."));

            default -> List.of();
        };
    }
}
