package fr.lapetina.music.concept;

import fr.lapetina.music.learner.ConceptMastery;
import fr.lapetina.music.learner.LearnerSnapshot;
import fr.lapetina.music.theory.AbcNotation;
import fr.lapetina.music.theory.Chord;
import fr.lapetina.music.theory.ChordAnalyzer;
import fr.lapetina.music.theory.ChordQuality;
import fr.lapetina.music.theory.Interval;
import fr.lapetina.music.theory.Inversion;
import fr.lapetina.music.theory.Key;
import fr.lapetina.music.theory.Mode;
import fr.lapetina.music.theory.PitchClass;
import fr.lapetina.music.theory.Scale;
import fr.lapetina.music.theory.ScaleType;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Teaches a concept, before anything is asked about it.
 *
 * <p>Every fact and every worked example is generated by the theory engine, so the lesson
 * and the marking cannot disagree. A language model is not involved: this is the part of
 * the application that must simply be right.
 */
@ApplicationScoped
public class LessonService {

    @Inject
    ConceptGraph conceptGraph;

    public Lesson lessonFor(String conceptId, LearnerSnapshot snapshot) {
        Concept concept = conceptGraph.require(conceptId);
        ConceptMastery mastery = snapshot.concept(conceptId);
        boolean ready = concept.prerequisites().stream().allMatch(snapshot::knows);

        return new Lesson(
                concept.id(),
                concept.name(),
                concept.description(),
                concept.category().name(),
                sectionsFor(conceptId),
                links(concept.prerequisites(), snapshot),
                links(conceptGraph.dependentsOf(conceptId).stream().map(Concept::id).toList(), snapshot),
                mastery.mastery(),
                mastery.state().name(),
                ready);
    }

    private List<Lesson.ConceptLink> links(List<String> ids, LearnerSnapshot snapshot) {
        List<Lesson.ConceptLink> links = new ArrayList<>();
        for (String id : ids) {
            ConceptMastery mastery = snapshot.concept(id);
            links.add(new Lesson.ConceptLink(id, mastery.name(), mastery.mastery(), mastery.isKnown()));
        }
        return List.copyOf(links);
    }

    private static String spell(Scale scale) {
        return scale.pitchClasses().stream().map(PitchClass::name).collect(Collectors.joining(" "));
    }

    private static String notes(Chord chord) {
        return chord.pitchClasses().stream().map(PitchClass::name).collect(Collectors.joining(" "));
    }

    private static String chordLine(Key key, int... degrees) {
        List<Chord> chords = new ArrayList<>();
        for (int degree : degrees) {
            chords.add(key.triad(degree));
        }
        return chords.stream().map(Chord::symbol).collect(Collectors.joining(" "));
    }

    private static List<Chord> chords(String... symbols) {
        return List.of(symbols).stream().map(ChordAnalyzer::parse).toList();
    }

    /** The body of the lesson, per concept. */
    List<LessonSection> sectionsFor(String conceptId) {
        Key c = Key.major("C");
        return switch (conceptId) {
            case "note" -> List.of(
                    LessonSection.of("Seven letters, then they repeat",
                            "Music uses only A B C D E F G. After G it starts again at A, an octave higher.",
                            "On a piano, the white keys are those seven letters. The black keys are the notes between."),
                    LessonSection.of("Sharps raise, flats lower",
                            "A sharp (#) raises a note by one semitone — the very next key up, black or white.",
                            "A flat (b) lowers it by one semitone.",
                            "So the black key between C and D is both C# and Db. Same key, two names."),
                    LessonSection.of("Why two names matter",
                            "F# and Gb sound identical but are not interchangeable. Which one is correct depends on the key you are in.",
                            "This is called spelling, and getting it wrong is the most common mistake in written harmony.")
                            .showing(AbcNotation.melody(List.of(
                                    fr.lapetina.music.theory.Note.parse("C4"),
                                    fr.lapetina.music.theory.Note.parse("C#4"),
                                    fr.lapetina.music.theory.Note.parse("D4"),
                                    fr.lapetina.music.theory.Note.parse("Eb4")), c, "Semitone steps"),
                                    "C, C sharp, D, E flat — each a semitone apart"));

            case "interval" -> List.of(
                    LessonSection.of("An interval is a distance, named twice over",
                            "Every interval has a number and a quality. The number counts letter names; the quality says exactly how wide.",
                            "C up to E spans C-D-E, three letters, so it is a third. It is four semitones wide, which makes it major.",
                            "C up to Eb is still a third — same three letters — but three semitones, which makes it minor."),
                    LessonSection.of("Perfect, major and minor",
                            "Unisons, fourths, fifths and octaves are perfect. Seconds, thirds, sixths and sevenths are major or minor.",
                            "Narrowing a perfect or minor interval makes it diminished. Widening any of them makes it augmented."),
                    LessonSection.of("Where spelling bites",
                            "C to F# is an augmented fourth. C to Gb is a diminished fifth. Both are six semitones.",
                            "They are different intervals because the letters differ, and they behave differently in harmony.")
                            .showing(AbcNotation.interval(fr.lapetina.music.theory.Note.parse("C4"),
                                    Interval.MAJOR_THIRD, c), "A major third above C"));

            case "major-scale" -> List.of(
                    LessonSection.of("One pattern, twelve keys",
                            "Tone, tone, semitone, tone, tone, tone, semitone. That pattern is the major scale, wherever you start.",
                            "C major: " + spell(Scale.of("C", ScaleType.MAJOR)) + " — the only one with no sharps or flats.",
                            "D major: " + spell(Scale.of("D", ScaleType.MAJOR)) + ". The pattern forces F# and C#."),
                    LessonSection.of("One note per letter",
                            "A major scale uses each letter exactly once. That is why F# major has an E#, not an F.",
                            "F# major: " + spell(Scale.of("F#", ScaleType.MAJOR)) + ".")
                            .showing(AbcNotation.scale(Scale.of("D", ScaleType.MAJOR), 4), "D major, ascending"));

            case "minor-scale" -> List.of(
                    LessonSection.of("Three forms, one tonic",
                            "Natural minor: " + spell(Scale.of("A", ScaleType.NATURAL_MINOR)) + ".",
                            "Harmonic minor raises the seventh: " + spell(Scale.of("A", ScaleType.HARMONIC_MINOR)) + ".",
                            "Melodic minor raises the sixth as well: " + spell(Scale.of("A", ScaleType.MELODIC_MINOR)) + "."),
                    LessonSection.of("Why the seventh gets raised",
                            "Without it there is no leading tone, and no semitone pulling up to the tonic.",
                            "Raising it also turns the chord on the fifth degree from minor into major, which is what makes a minor key sound like it has a dominant.")
                            .showing(AbcNotation.scale(Scale.of("A", ScaleType.HARMONIC_MINOR), 4),
                                    "A harmonic minor — note the G sharp"));

            case "triad" -> List.of(
                    LessonSection.of("Two thirds, stacked",
                            "Take a note, add a third above it, then another third above that. That is a triad.",
                            "Which thirds you stack decides the quality."),
                    LessonSection.of("The four qualities",
                            "Major: " + notes(Chord.of("C", ChordQuality.MAJOR)) + " — major third, then minor third.",
                            "Minor: " + notes(Chord.of("C", ChordQuality.MINOR)) + " — minor third, then major third.",
                            "Diminished: " + notes(Chord.of("C", ChordQuality.DIMINISHED)) + " — two minor thirds.",
                            "Augmented: " + notes(Chord.of("C", ChordQuality.AUGMENTED)) + " — two major thirds.")
                            .showing(AbcNotation.progression(chords("C", "Cm", "Cdim", "Caug"), c, 3),
                                    "The same root, four qualities"));

            case "chord-inversion" -> List.of(
                    LessonSection.of("The bass decides",
                            "A chord is inverted when something other than the root is the lowest note.",
                            "G major has the notes G B D. In root position G is lowest; in first inversion B is; in second inversion D is.",
                            "The order of the notes above the bass makes no difference at all."),
                    LessonSection.of("How they are written",
                            "First inversion is figured 6, second inversion 6/4. In lead sheets you will see G/B and G/D.",
                            "For seventh chords the figures are 7, 6/5, 4/3 and 4/2 from root position downwards.")
                            .showing(AbcNotation.progression(chords("G", "G/B", "G/D"), c, 3),
                                    "G major: root position, first inversion, second inversion"));

            case "seventh-chord" -> List.of(
                    LessonSection.of("A third on top of a triad",
                            "Add one more third above a triad and you have a seventh chord.",
                            "Dominant seventh: " + notes(Chord.of("G", ChordQuality.DOMINANT_SEVENTH)) + " — major triad, minor seventh.",
                            "Major seventh: " + notes(Chord.of("C", ChordQuality.MAJOR_SEVENTH)) + " — major triad, major seventh.",
                            "Minor seventh: " + notes(Chord.of("D", ChordQuality.MINOR_SEVENTH)) + " — minor triad, minor seventh."),
                    LessonSection.of("The two diminished kinds",
                            "Half-diminished: " + notes(Chord.of("B", ChordQuality.HALF_DIMINISHED_SEVENTH)) + " — diminished triad, minor seventh.",
                            "Fully diminished: " + notes(Chord.of("B", ChordQuality.DIMINISHED_SEVENTH)) + " — diminished triad, diminished seventh.")
                            .showing(AbcNotation.progression(chords("Cmaj7", "Dm7", "G7", "Bm7b5"), c, 3),
                                    "Four seventh chords from C major"));

            case "roman-numeral" -> List.of(
                    LessonSection.of("Numbering chords, not notes",
                            "A Roman numeral names a chord by the scale degree it is built on, so harmony can be described in any key at once.",
                            "Upper case means a major third in the chord, lower case a minor one. A small circle means diminished."),
                    LessonSection.of("The seven of a major key",
                            "In C major: " + chordLine(c, 1, 2, 3, 4, 5, 6, 7),
                            "Numbered: I ii iii IV V vi vii°. That pattern of qualities is the same in every major key.")
                            .showing(AbcNotation.progression(c.diatonicTriads(), c, 3),
                                    "The seven diatonic triads of C major"));

            case "dominant-seventh" -> List.of(
                    LessonSection.of("The chord that has to move",
                            "V7 is built on the fifth degree: in C major, " + notes(c.dominantSeventh()) + ".",
                            "Inside it sits a tritone — between the third and the seventh — and that interval is unstable."),
                    LessonSection.of("How it resolves",
                            "The third is the leading tone and rises a semitone to the tonic.",
                            "The seventh falls a step to the third of the tonic chord.",
                            "In C: B rises to C, F falls to E. Both move as little as possible.")
                            .showing(AbcNotation.progression(List.of(c.dominantSeventh(), c.tonicTriad()), c, 3),
                                    "G7 resolving to C"));

            case "cadence" -> List.of(
                    LessonSection.of("How a phrase ends",
                            "A cadence is the harmonic punctuation at the end of a phrase, and how strongly it closes.",
                            "Perfect authentic: V to I, both in root position. The strongest ending there is.",
                            "Half: the phrase stops on V. Unfinished, and meant to be.",
                            "Plagal: IV to I. The amen.",
                            "Deceptive: V to vi. Sets up the ending, then withholds it.")
                            .showing(AbcNotation.progression(chords("F", "G", "C"), c, 3),
                                    "IV V I — a perfect authentic cadence in C"));

            case "extended-chord" -> List.of(
                    LessonSection.of("Keep stacking thirds",
                            "Above the seventh come the ninth, the eleventh and the thirteenth.",
                            "C9: " + notes(Chord.of("C", ChordQuality.DOMINANT_NINTH)) + ".",
                            "Cmaj9: " + notes(Chord.of("C", ChordQuality.MAJOR_NINTH)) + ".",
                            "C13: " + notes(Chord.of("C", ChordQuality.DOMINANT_THIRTEENTH)) + "."),
                    LessonSection.of("Sixths are not sevenths",
                            "C6 is " + notes(Chord.of("C", ChordQuality.MAJOR_SIXTH)) + " — a triad with a sixth added, not a chord with a seventh.",
                            "It is a resting chord where a seventh would want to move.")
                            .showing(AbcNotation.progression(chords("C6", "C9", "Cmaj9"), c, 3),
                                    "C6, C9 and Cmaj9"));

            case "altered-dominant" -> List.of(
                    LessonSection.of("Sharpening the tension",
                            "A dominant already wants to resolve. Altering its ninth, eleventh or thirteenth makes it want to more.",
                            "C7b9: " + notes(Chord.of("C", ChordQuality.DOMINANT_FLAT_NINTH)) + ".",
                            "C7#9: " + notes(Chord.of("C", ChordQuality.DOMINANT_SHARP_NINTH)) + ".",
                            "C7#11: " + notes(Chord.of("C", ChordQuality.DOMINANT_SHARP_ELEVENTH)) + ".",
                            "C7b13: " + notes(Chord.of("C", ChordQuality.DOMINANT_FLAT_THIRTEENTH)) + "."),
                    LessonSection.of("Spelling still matters",
                            "The sharp ninth of C7 is D#, not Eb. It is a raised second degree, so it is spelled as one.",
                            "The chord still functions as a dominant: the alterations sharpen it, they do not change its job."));

            case "two-five-one" -> List.of(
                    LessonSection.of("The sentence jazz is written in",
                            "ii-V-I is a predominant, then a dominant, then home — the same shape as classical harmony, with sevenths on everything.",
                            "In C: Dm7 G7 Cmaj7. In F: Gm7 C7 Fmaj7. In Bb: Cm7 F7 Bbmaj7."),
                    LessonSection.of("Why it holds together",
                            "Each chord's seventh falls a semitone and lands on the next chord's third.",
                            "In C: the seventh of Dm7 is C, and it falls to B, the third of G7. The seventh of G7 is F, and it falls to E, the third of Cmaj7.",
                            "That chain of falling sevenths is the whole mechanism, and it is why the progression feels inevitable rather than merely conventional.",
                            "In a minor key the ii is half-diminished: Dm7b5 G7 Cm7.")
                            .showing(AbcNotation.progression(chords("Dm7", "G7", "Cmaj7"), c, 3),
                                    "ii-V-I in C major"));

            case "tritone-substitution" -> List.of(
                    LessonSection.of("Two dominants, one tritone",
                            "G7 contains B and F. Db7 contains F and Cb, which sounds the same as B.",
                            "They share the tritone that wants to resolve, so either can resolve to C."),
                    LessonSection.of("What changes",
                            "The bass. Instead of falling a fifth from G to C, it slides a semitone from Db to C.",
                            "In C major, Dm7 Db7 Cmaj7 is a ii-V-I with the dominant substituted.")
                            .showing(AbcNotation.progression(chords("Dm7", "Db7", "Cmaj7"), c, 3),
                                    "ii-V-I with a tritone substitution"));

            case "counterpoint" -> List.of(
                    LessonSection.of("Two lines, both alive",
                            "Counterpoint is two melodies heard at once, each one worth listening to on its own.",
                            "What keeps them independent is how they move in relation to each other."),
                    LessonSection.of("Four motions",
                            "Parallel: both move the same way, keeping the same interval.",
                            "Similar: both move the same way, but the interval changes.",
                            "Contrary: they move in opposite directions. The most independent.",
                            "Oblique: one moves, the other holds."),
                    LessonSection.of("The forbidden parallel",
                            "Two voices moving from a perfect fifth straight into another perfect fifth stop sounding like two voices.",
                            "Same for octaves. Parallel thirds and sixths are fine, and common.",
                            "Reach a perfect consonance by contrary motion instead."));

            case "species-counterpoint" -> List.of(
                    LessonSection.of("First species: note against note",
                            "One note in your line for each note of the given melody, the cantus firmus.",
                            "Every one of them a consonance."),
                    LessonSection.of("What counts as consonant",
                            "Unisons, thirds, perfect fifths, sixths and octaves.",
                            "Seconds, fourths, sevenths and any tritone are dissonant and are not allowed here."),
                    LessonSection.of("Beginning and ending",
                            "Start on a perfect consonance and end on one.",
                            "Approach the final by contrary motion, and prefer contrary motion throughout."));

            default -> List.of();
        };
    }
}
