package fr.lapetina.music.concept;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import fr.lapetina.music.learner.LearnerService;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * The reading half of the application. Everything a lesson states is generated by the
 * theory engine, so these check the engine's own output rather than prose someone typed.
 */
@QuarkusTest
class LessonServiceTest {

    @Inject
    LessonService lessonService;

    @Inject
    LearnerService learnerService;

    @Inject
    ConceptGraph conceptGraph;

    private Lesson lesson(String conceptId) {
        return lessonService.lessonFor(conceptId, learnerService.snapshot(learnerService.current()));
    }

    @Test
    @DisplayName("a lesson explains before anything is asked, with worked notation")
    void teachesWithExamples() {
        Lesson triads = lesson("triad");
        assertEquals("Triads", triads.name());
        assertTrue(triads.sections().size() >= 2);
        assertTrue(triads.sections().stream().anyMatch(section -> section.abc() != null),
                "no worked example in notation");
        assertTrue(String.join(" ", triads.sections().get(1).points()).contains("C E G"));
    }

    @Test
    void spellsJazzAndCounterpointCorrectly() {
        String extended = String.join(" ", lesson("extended-chord").sections().stream()
                .flatMap(section -> section.points().stream()).toList());
        assertTrue(extended.contains("C E G Bb D"), extended);

        String altered = String.join(" ", lesson("altered-dominant").sections().stream()
                .flatMap(section -> section.points().stream()).toList());
        assertTrue(altered.contains("D#"), altered);
        assertTrue(altered.contains("not Eb"), altered);

        String counterpoint = String.join(" ", lesson("counterpoint").sections().stream()
                .flatMap(section -> section.points().stream()).toList());
        assertTrue(counterpoint.contains("Contrary"), counterpoint);
    }

    @Test
    @DisplayName("a lesson says what it rests on and what it opens up")
    void placesTheConceptInTheGraph() {
        Lesson lesson = lesson("dominant-seventh");
        assertTrue(lesson.restsOn().stream().anyMatch(link -> link.conceptId().equals("seventh-chord")));
        assertTrue(lesson.opensUp().stream().anyMatch(link -> link.conceptId().equals("secondary-dominant")));
        assertFalse(lesson.ready(), "nothing is known yet, so this should not read as ready");
    }

    @Test
    void everyConceptReturnsALessonWithoutFailing() {
        for (Concept concept : conceptGraph.all()) {
            Lesson lesson = lesson(concept.id());
            assertEquals(concept.id(), lesson.conceptId());
            assertFalse(lesson.summary().isBlank(), concept.id());
        }
    }
}
