import { useQuery } from '@tanstack/react-query'
import { api } from '../api/client'
import { Score } from '../components/Score'
import { CorpusExample } from '../components/CorpusExample'

interface LessonViewProps {
  conceptId: string
  onBack: () => void
  onPractise: (conceptId: string) => void
  onAsk: (conceptId: string, question: string) => void
  onOpen: (conceptId: string) => void
}

/**
 * The concept, taught.
 *
 * Everything on this page — every note name, every worked example — is generated by the
 * theory engine that also marks the answers, so what you read here and what you are
 * marked against cannot disagree.
 */
export function LessonView({ conceptId, onBack, onPractise, onAsk, onOpen }: LessonViewProps) {
  const { data, isLoading, error } = useQuery({
    queryKey: ['lesson', conceptId],
    queryFn: () => api.lesson(conceptId),
  })

  if (isLoading) {
    return <div className="view">Loading the lesson…</div>
  }
  if (error || !data) {
    return <div className="view view-error">That lesson could not be loaded.</div>
  }

  const missing = data.restsOn.filter((link) => !link.known)

  return (
    <div className="view view-lesson">
      <button type="button" className="back" onClick={onBack}>
        ← All topics
      </button>

      <header className="lesson-head">
        <span className="tag tag-accent">{data.category.replace('_', ' ').toLowerCase()}</span>
        <h1>{data.name}</h1>
        <p className="lesson-summary">{data.summary}</p>
      </header>

      {missing.length > 0 && (
        <div className="notice">
          This rests on{' '}
          {missing.map((link, index) => (
            <span key={link.conceptId}>
              {index > 0 && ', '}
              <button type="button" className="link" onClick={() => onOpen(link.conceptId)}>
                {link.name}
              </button>
            </span>
          ))}
          . You can read this now, but the tutor will start you there.
        </div>
      )}

      {data.sections.length === 0 && (
        <p className="muted">
          There is no written lesson for this one yet — work on it with the tutor and ask as you go.
        </p>
      )}

      {data.sections.map((section) => (
        <section className="lesson-section" key={section.heading}>
          <h2>{section.heading}</h2>
          <ul>
            {section.points.map((point) => (
              <li key={point}>{point}</li>
            ))}
          </ul>
          {section.abc && (
            <figure className="example">
              <Score abc={section.abc} />
              {section.caption && <figcaption>{section.caption}</figcaption>}
            </figure>
          )}
        </section>
      ))}

      <section className="lesson-examples">
        <h2>In real music</h2>
        <p className="hint">
          Passages from annotated scores, cited so you can look them up. Nothing here is
          written by the tutor.
        </p>
        <CorpusExample conceptId={data.conceptId} />
      </section>

      <section className="lesson-next">
        <h2>Now try it</h2>
        <div className="lesson-actions">
          <button type="button" className="btn-primary" onClick={() => onPractise(data.conceptId)}>
            Practise this
          </button>
          <button
            type="button"
            className="btn-ghost"
            onClick={() => onAsk(data.conceptId, `Can you explain ${data.name.toLowerCase()} to me?`)}
          >
            Ask the tutor about it
          </button>
        </div>
      </section>

      {data.opensUp.length > 0 && (
        <section className="lesson-section">
          <h2>What this opens up</h2>
          <div className="chips">
            {data.opensUp.map((link) => (
              <button key={link.conceptId} type="button" className="chip-link" onClick={() => onOpen(link.conceptId)}>
                {link.name}
              </button>
            ))}
          </div>
        </section>
      )}
    </div>
  )
}
